### ISSUE TITLE
Отсутствие существующего игрока 

### ISSUE THREAD

**Issue by Pelemenka337** [SamotXave/Logger#1]
Открыл logger, вкладку PlayerDrop
![image](https://user-images.githubusercontent.com/64261220/146994682-e099b70b-0981-47d9-aead-b2def774b341.png)
Ввел ник существующего игрока и ничего не выдало.
![image](https://user-images.githubusercontent.com/64261220/146994716-f157ce7c-d034-4d5e-8af2-6f791535d133.png)
Нужно сделать исключение, или же дописать код, для поиска только по нику.

**Comment by SamotXave** [comment]
Добавил выборку, которая осуществляет поиск всех данных по никнейму игрока.

**Comment by IlyaSoko** [comment]
Открыл logger,вкладку PlayerDrop и для определенного ника вывел все его действия за 21 число
![image](https://user-images.githubusercontent.com/90313338/147007336-86f44a96-7ab2-4b39-92c8-137f2fc4e35a.png)
Для вывода использовал данные с определенного сервера указанных в Settings
![image](https://user-images.githubusercontent.com/90313338/147007476-68ad7de8-7e55-4b13-8804-62804836049f.png)
Далее,заменил ссылки на сервер в Settings и нажал кнопку SaveUrl
![image](https://user-images.githubusercontent.com/90313338/147007589-3ca4090d-7a96-4110-9535-a52b0b730c6c.png)
После данной манипуляции попробовал для этого же ника и на эту же дату вывести его действия во вкладке PlayerDrop
![image](https://user-images.githubusercontent.com/90313338/147007751-a6ae25e3-9e1a-4449-8bac-03dcce622005.png)
В итоге вывелось то же самое,проверим что должно было вывести через логи
![image](https://user-images.githubusercontent.com/90313338/147007847-f3a74536-5e51-4522-b94d-81698491ece4.png)
Видно,что за 21 число не было ни одного действия,но данный ник существует на сервере.

Нужно дописать код,вероятнее всего не работает кнопка SaveUrl. Либо при несуществующих значениях программа выводит последний получившийся результат.
